### ISSUE TITLE
Tests (update please as we go)

### ISSUE THREAD

**Issue by mikejbuckingham** [medInria/medInria-public#292] opened 2016-02-18 17:28 UTC
So as requested, can we get people to test the following:

medInria compiles on Windows, Linux and MacOS
medInria correctly loads all plugins

All medInria filters work as expected:
    Add
    Divide
    Gaussian
    Invert
    Multiply
    Median
    Normalize
    Subtract
    Windowing

Visualiation works as expected (2d, 3d) on all OSes and both Intel and nVidia chipsets
Visualisation performance has not significantly degraded from VTK5 (medInria 2.2.1)

Composer provides full functionality
Presenter vs Port for parameters correctly values Port over Presenter
All nodes have the correct ports and presenters
Compositions work as expected, end-to-end

Please also play around with the app and report all crashes, weird behaviours, etc.

**Comment by ocommowi** [comment] 2016-02-19 08:25
Hey,  I had been playing around with a previous version and noted quite a few bugs in issue #261 . Could you merge those two issues (and may be tick what you have finished, I believe there are many) ? Thanks and great job by the way !

**Comment by ocommowi** [comment] 2016-02-26 08:23
First list of bugs from my side (moved from #261)

  - [ ] Paint segmentation does not work anymore with VTK7 compatible views (image is created without a name and painting is not there)
  - [ ] saving a loaded file to database makes its thumbnail disappear (written in the right folder but not found later on)
  - [ ] closing the last view of a tab leaves it in an awkward situation: not going back to base mode of the tab, just leaving it empty and not closable
  - [ ] the composer does not appear in bottom left menu and neither in all places where areas and workspaces are listed
  - [ ] Composer stylesheet to update
  - [ ] Ctrl + Space menu missing icon for generic workspace, composer missing as well
  - [ ] Going to the finder in browser on Mac makes the app crash
  - [ ] home page : generic does not appear in any category, clinical is empty
  - [ ] dropping a tensor image (or any glyph based image) in an empty view generates a lot of warnings in the console
  - [ ] stylesheet of combo box is wrong (eg selecting a plugin), probably some others as well
  - [ ] Diffusion tractography fails when a tensor is negative (TTK related, I'll handle it)
  - [ ] Generic, filtering and diffusion workspaces probably do something wrong when loading plugin processes or handling them: when quitting the app after using one plugin in those workspaces, there is a crash
  - [ ] Regression in diffusion workspace: in diffusion estimation, we cannot anymore do a brain masking plus model estimation. This would require an abstraction on its own, not sure yet how to handle this
  - [ ] Switch to four views leads to unequal splitting of the container in 4 parts. In a more general way, spliiting is somewhat broken, sometimes the size equalizer button doesn't work, sometimes dropping an image inside an empty view makes it bigger, ...
  - [ ] Some view interaction glitches: for example drop the 4d image of the heart, then the heart mesh. If you interact with the view, it will change the window level of the first layer (image) even though the mesh is selected on the right. In addition if that view is linked to others (eg do a 4 view split after dropping the two data), then this window leveling is not synchronized with the others
  - [ ] Drop the 4d heart image, switch to 3d mode, click on play in the navigator -> the image doesn't move. It does work in 2d but not 3d anymore...
  - [ ] Missing labels for parameters in filtering (probably diffusion as well) toolboxes, "change me" tooltips for many of them
  - [ ] We've lost the about plugins buttons. We should put them back

**Comment by mikejbuckingham** [comment] 2016-02-29 13:54
- [ ] saving a loaded file to database makes its thumbnail disappear (written in the right folder but not found later on)
  - [ ] the composer does not appear in bottom left menu and neither in all places where areas and workspaces are listed
  - [ ] Composer stylesheet to update
  - [ ] Ctrl + Space menu missing icon for generic workspace, composer missing as well
  - [ ] home page : generic does not appear in any category, clinical is empty
  - [ ] stylesheet of combo box is wrong (eg selecting a plugin), probably some others as well
  - [ ] Missing labels for parameters in filtering (probably diffusion as well) toolboxes, "change me" tooltips for many of them
  - [ ] We've lost the about plugins buttons. We should put them back
  - [ ] Generic, filtering and diffusion workspaces probably do something wrong when loading plugin processes or handling them: when quitting the app after using one plugin in those workspaces, there is a crash

**Comment by ocommowi** [comment] 2016-03-01 09:25
A few more bugs for those who would be looking for stuff to do :)

- [ ] Multi-layering ugly bug: drop an image, and another one in overlay, then remove the top layer in the layer settings toolbox. You get the only layer left having a transparency over it (image almost not visible)
- [ ] Quitting by Cmd+Q (Alt+F4 on win) doesn't ask for saving non persistent datasets
- [ ] If visu workspace selected as default in settings, going to segmentation when opening the app

**Comment by LoicCadour** [comment] 2016-03-15 14:03
Once you've seen your data in VR, changing the orientation is quite slow, slicing is very slow.
It's also happened to me since I am using VTK7 for MUSIC.

**Comment by Florent2305** [comment] 2017-11-17 09:46
- [ ] Remove deprecated VTK VR modes
- [ ] Add new VTK VR modes if they are available

**Comment by Florent2305** [comment] 2017-11-28 09:53
- [ ] Check memory leaks.
- [ ] Check memory over consuming (free memory too late, not just in time).
- [ ] Remove old test suite.
- [ ] Re implement a valid test suite.
- [ ] Pretty print all code with the same policy.
- [ ] In header files put the "#pragma once" on the first line, befor any comments or licence comment.
- [ ] Remove multiple and different log system and use an unique one.
- [ ] Remove export macro into internals class of plugins.
- [ ] Simplify all visualization plugins because they are over ingegerd after separation of some class from medVtkInria .
- [ ] Define clearly APIs of vizu plugins, internal modules, etc. And document its well with doxygen.

**Comment by alegouhy** [comment] 2017-12-05 14:16
propostition: add feature to select fiducial points

**Comment by ocommowi** [comment] 2018-01-05 08:57
Two new view bugs following our modifications:
- [ ] Double clicking somewhere on a view does not move the axes anymore (neither the linked ones)
- [ ] 4D views time changing is wrong (compared to medinria 2 which works fine)

**Comment by Florent2305** [comment] 2018-01-17 11:14
- [ ] dropping a tensor image (or any glyph based image) in an empty view generates a lot of warnings in the console. This seems to happen only when the image voxel size is not 1 though
- [ ] Remaining bug from previous: drop the 4d image of the heart, then the heart mesh. If you interact with the view, it will change the window level of the first layer (image) even though the mesh is selected on the right. That bug was already there in medinria 2 though
- [ ] A new one on visualisation: not sure if it is due to vtk or us, view a set of fibers in 3d has a problem of transparency when you rotate around the fibers
- [ ] saving a loaded file to database makes its thumbnail disappear (written in the right folder but not found later on)
- [ ] Composer stylesheet to update
- [ ] stylesheet of combo box is wrong (eg selecting a plugin), probably some others as well
- [ ] We've lost the about plugins buttons. We should put them back
- [ ] If visu workspace selected as default in settings, going to segmentation when opening the app or even crashing in some cases
- [ ] Some of the shortcuts listed here https://med.inria.fr/docs/51-doc-shortcuts do not work anymore. For some, the regression may have happened before the dev branch, for some others they may just be outdated, but it's worth verifying

**Comment by Florent2305** [comment] 2020-03-18 13:19
Too old. I closed it

**Comment by Florent2305** [comment] 2020-03-18 13:19
Too old. I closed it

**Closed by Florent2305** 2020-03-18 13:19 UTC
